# Generated by Django 4.2.7 on 2023-11-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('cep', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=2)),
                ('streetName', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
