# Generated by Django 4.2.7 on 2023-12-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='Address',
        ),
    ]
